### ISSUE TITLE
Composer needs package check

### ISSUE THREAD

**Issue by nadirhamid** [bandwidthcom/php-bandwidth#1]
when using "composer require bandwidth/catapult"

the returned result is sometimes "Nothing to install or update" this
needs to be looked into.

**Comment by smitchell2240** [comment]
What does it mean? Is that something on how git is setup or how we've
published to composer?

Steve

On Mon, Mar 23, 2015 at 1:14 PM, Nadir Hamid <notifications@github.com>
wrote:

> when using "composer require bandwidth/catapult"
>
> the returned result is sometimes "Nothing to install or update" this
> needs to be looked into.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandwidthcom/php-bandwidth/issues/1>.
>



-- 

Steve Mitchell

*Director, Solutions Planning*

Bandwidth <http://www.bandwidth.com/business/>

o 303.228.8849

m 719.640.1056

e  smitchell@bandwidth.com

**Comment by nadirhamid** [comment]
Hi Steve,

Recently I setup the autohooks feature for composer and since
the package has been throwing errors. I am currently in process
of looking in this. I will keep updating

**Comment by smitchell2240** [comment]
Got it! Thanks!

Steve

On Mon, Mar 23, 2015 at 2:21 PM, Nadir Hamid <notifications@github.com>
wrote:

> Hi Steve,
>
> Recently I setup the autohooks feature for composer and since
> the package has been throwing errors. I am currently in process
> of looking in this. I will keep updating
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandwidthcom/php-bandwidth/issues/1#issuecomment-85176561>
> .
>



-- 

Steve Mitchell

*Director, Solutions Planning*

Bandwidth <http://www.bandwidth.com/business/>

o 303.228.8849

m 719.640.1056

e  smitchell@bandwidth.com

**Comment by nadirhamid** [comment]
- Update

Catapult Composer Package should be working again

**Comment by smitchell2240** [comment]
Thanks much, Nadir!

Steve

On Mon, Mar 23, 2015 at 7:37 PM, Nadir Hamid <notifications@github.com>
wrote:

>
>    - Update
>
> Catapult Composer Package should be working again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandwidthcom/php-bandwidth/issues/1#issuecomment-85283533>
> .
>



-- 

Steve Mitchell

*Director, Solutions Planning*

Bandwidth <http://www.bandwidth.com/business/>

o 303.228.8849

m 719.640.1056

e  smitchell@bandwidth.com
