### ISSUE TITLE
credentials.json

### ISSUE THREAD

**Issue by coldlamper** [bandwidthcom/php-bandwidth#11]
I don't seem to be able to get around not having this file. The documentation implies that if you supply the credentials to the credentials constructor like
```
$cred = new Catapult\Credentials($bandwidth_user_id, $bandwidth_api_token, $bandwidth_api_secret);
```
then you do not need the file.  If you look at the constructor
```
public function __construct($user_token='',
              $api_token='',
              $api_secret='') 
    { 
      $file = self::$credentials_opts['file'];

      /* only consider parameter init if all provided */
      if (isset(self::$credentials_opts['path'])) {
        self::$credentials_opts['path'] = self::$credentials_opts['path'] . DIRECTORY_SEPARATOR . self::$credentials_opts['file'];
      } else {
        self::$credentials_opts['path'] = realpath(getcwd()) . DIRECTORY_SEPARATOR . self::$credentials_opts['file'];
      }

      /**
       * check if the file is accessible
       * when it is "credentials.json"
       * this should 
       *
       * this needs to only validate the directory
       */
      if (!is_file(self::$credentials_opts['path'])) {
        throw new \CatapultApiException("$file was not found in directory " . self::$credentials_opts['path']);
      }
       
      if ($user_token && $api_token && $api_secret)
        $this->credentials = new CredentialsUser($user_token, $api_token, $api_secret);
      else
        $this->credentials = file_get_contents(self::$credentials_opts['path']);
    } 
```
it checks for the file no matter what.  Would it be possible to change it so we do not have to provide the credentials.json file?

**Comment by smitchell2240** [comment]
That's great feedback! Thanks much!

We'll try to get to this quickly, but are in the middle of vacations and such that will push any changes into August. If you need it sooner, feel free to create PR and we'll get your changes merged. 

Steve

**Comment by nadirhamid** [comment]
p.s

Catapult\Credentials used directly was in 0.5.0

in 0.7.0 you can just use

Catapult\Client($credientials);

or
Catapult\Client('BANDWIDTH_USER_ID', 'BANDWIDTH_USER_TOKEN',
'BANDWIDTH_USER_SECRET');

It should not always check for the file this way

**Comment by coldlamper** [comment]
I used **composer require bandwidth/catapult** to install.  The version installed was 0.7.3 which doesn't seem to contain the code to handle
```
Catapult\Client('BANDWIDTH_USER_ID', 'BANDWIDTH_USER_TOKEN',
'BANDWIDTH_USER_SECRET');
```
 correctly without the credentials.json.  I changed my composer.json to use  dev-master instead of ^0.8.0. That gets the 0.8.0 release.  It looks like to me that the 0.8.0 tag points to a 0.7.3 release.

**Comment by nadirhamid** [comment]
Hi Coldlamper,

Currently the default is the 0.7.3 tag. 0.8.0 included some patches, see here:
https://github.com/bandwidthcom/php-bandwidth/blob/master/CHANGELOG

**Comment by soundslocke** [comment]
Shouldn't the default be the 0.8.0 tag now?

**Comment by shaneneuerburg** [comment]
Is there a release planned to resolve this? I'm still seeing this on the latest 0.8.0 release. I don't want to point to dev-master if I can avoid it.

**Comment by dtolb** [comment]
@soundslocke @shaneneuerburg @coldlamper I'm investigating this now. 

Is anyone actually using the creds.json file? Seems like a bad pattern to have in place.

**Comment by soundslocke** [comment]
Thanks for the update. We've been used the {{dev-master}} version via Composer for over a year now in order to get the correct 0.8.0 version (which was seemingly never tagged/released).

We're not using the credentials.json file, which does seem like a bad practice.

**Comment by shaneneuerburg** [comment]
@dtolb I think it makes more sense to let the developer figure out what architecture to store the credentials in. If someone wants to use a json file, they can load their own and feed the values into the client.

**Comment by dtolb** [comment]
Sorry guys for the seemingly little ❤️  here. I'm going to be taking look at updating the SDK. It's really just two of us right now supporting all the SDKs and SDK examples and some other things. So bear with us as things move here. 

Updated version is now [0.8.1](https://packagist.org/packages/bandwidth/catapult#0.8.1) Pointing to this [commit](https://github.com/bandwidthcom/php-bandwidth/commit/e90ed358e2eb8cb163425d7ec88e7e028988aaa0) 

As part of our refresh are there any PHP SDK patterns that you would like us to follow? Obviously we could copy the [other guy's sdk](https://github.com/twilio/twilio-php) where possible, but I want to get some feedback to make sure we're giving y'all what you want.

**Comment by shaneneuerburg** [comment]
I'm not necessarily looking for a re-write, but the documentation could definitely use a facelift. I'm doing a lot of experimenting trying to figure out what in the world is going on. It's a bit too abstract for the sparse documentation IMO :)

**Comment by dtolb** [comment]
@shaneneuerburg Truf

**Comment by dtolb** [comment]
@shaneneuerburg @soundslocke @coldlamper moving discussion to [new issue](https://github.com/bandwidthcom/php-bandwidth/issues/17) feel free to chime in there :)
