### ISSUE TITLE
function: post_messages not found in Catapult\MessageMulti

### ISSUE THREAD

**Issue by dnwk** [bandwidthcom/php-bandwidth#18]
Saw this error when trying to use MessageMulti to send multiple messages.

**Comment by dnwk** [comment]
Line 71 on MessageMulti.php there is a method misspelled. 
      $msgs = $this->post_messages();  
should be       $msgs = $this->postMessages();

**Comment by dtolb** [comment]
@dnwk just got back from vacation. I'll fix this ASAP

**Comment by dnwk** [comment]
Thanks

**Comment by dtolb** [comment]
Fixed https://packagist.org/packages/bandwidth/catapult#0.8.2
