### ISSUE TITLE
Getting Text message was too long error

### ISSUE THREAD

**Issue by dnwk** [bandwidthcom/php-bandwidth#27]
I was getting this error message when sending text message

(line: 84) - APPLICATION: [Jan/01/17:18:51:18] - Text message was too long. use: warn[FALSE] to omit.

I only have 165 characters in the message. I think the API supposedly should accept strings up to 2048, right?

**Comment by dnwk** [comment]
types/TextMessage.php hard limit the message to 157 characters. It needs to be updated.

**Comment by Adam-Baldwin-LQM** [comment]
I'm running into this issue also. Any resolution?

**Comment by tylercd100** [comment]
Just made a PR, hopefully we can get some eyes on it

**Comment by dtolb** [comment]
Will merge soon! Thanks @tylercd100
