### ISSUE TITLE
Migrate BXML/BAML to <Response> instead of <Request>

### ISSUE THREAD

**Issue by jasommerset** [bandwidthcom/php-bandwidth#3]
Testing this, BAML is producing <Request> when it should generate <Response>

e..g http://ap.bandwidth.com/docs/xml/gather/

I ran this example
$ php sample-baml.php Gather requestUrl http://hello.com

The following BaML was generated:
<?xml version=“1.0” encoding=“UTF-8”?><Request><Gather requestUrl=“http://hello.com”>example</Gather></Request>

Should be 
<?xml version=“1.0” encoding=“UTF-8”?><Response><Gather requestUrl=“http://hello.com”>example</Gather></Response>

**Comment by nadirhamid** [comment]
Default constructor should now be <Response>
