### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by tmorren** [bandwidthcom/php-bandwidth#33]
Can you guys issue a new release? The last release was almost a year ago, so when I run composer update, it's not getting the latest changes (the character limit). Thanks!

**Comment by tylercd100** [comment]
:+1: +1

**Comment by dtolb** [comment]
Easy enough. Release [v0.9.2](https://github.com/bandwidthcom/php-bandwidth/releases/tag/v0.9.2) is live on [packagist](https://packagist.org/packages/bandwidth/catapult#v0.9.2)
